### PR TITLE
query string

### PR DESCRIPTION
**Pull request by santanaruben**
Hi Isaac, nice work, is it possible to use the address as URL parameter? 
That way we could assign automatic URLs to each profile.

### CODE REVIEW

**Review by isaac-art — APPROVED** [review]
looks good to me, thanks! :)

**Comment by isaac-art** [comment]
oh im only half awake... this will clash with the routing on fastapi. 

will have a think, should be able to tweak it to work!

**Comment by isaac-art** [comment]
works ok, maybe i'll add an extra loading spinner if it already has an address: http://faces.humanity.tools/?address=0x601729acddb9e966822a90de235d494647691f1d

**Comment by santanaruben** [comment]
Yeah, I think it is a must

**Pull request merged**
